### ISSUE TITLE
Add support for GO 1.23

### ISSUE THREAD

**Issue by ovechkin-dm** [ovechkin-dm/go-dyno#3]
Golang removed support for //go:linkname directive. That means that another workaround should be implemented.

**Comment by m1khal3v** [comment]
@ovechkin-dm Thank you for the wonderful mockio library, I couldn’t stay away and started intensively Googling what other options there are. I found information that previously assembly stubs were used for the same purposes

https://sitano.github.io/2016/04/28/golang-private/

I hope this helps somehow

**Comment by ovechkin-dm** [comment]
Hello @m1khal3v 
Thank you for your research. Unfortunately, accroding to [changelog](https://tip.golang.org/doc/go1.23), assembly stubs are also not allowed. `Similarly, the linker disallows references to such symbols from assembly code` 

There are couple of good news though:
1. I am half way done with the workaround
2. For now you can run tests with flag, and it will work `go test -ldflags=-checklinkname=0 ./...`

**Comment by ovechkin-dm** [comment]
Fixed in v0.3.0
